### PR TITLE
Fix: Nx.to_scalar in examples

### PR DESCRIPTION
**Pull request by floatn**
`Nx.to_scalar/1` has been renamed to `Nx.to_number/1`

### CODE REVIEW

**Review by seanmor5 — COMMENTED** [review]
Thank you! A quick note - you can remove log_iteration from xor. That's from an earlier iteration and is no longer necessary

**Comment by floatn** [comment]
@seanmor5 
Don't see such function in `xor.exs`. Did you mean `mnist_gan` example? It's used in a `Loop.log` there.

**Comment by seanmor5** [comment]
It is the log_metrics function

**Comment by floatn** [comment]
Oh. I see. `log_metrics` doesn't work atm. Don't we need logs in xor example? How about I just fix it?

**Pull request merged**
