### PR TITLE
Datasets reorganization

### PR DESCRIPTION
**Pull request by t-rutten**
Here we've moved code for downloading and handling the CIFAR, MNIST, and FashionMNIST datasets used by the example scripts into separate modules under `Axon.Data`.

Most of the change are reorganization and de-duplication of code for downloading and processing datasets, but we also add options to change the batch size as well as the directory where datasets are stored. This allows for calls like

```elixir
Axon.Data.MNIST.download_images(data_path: 'tmp/my_data/mnist', batch_size: 200)
```

The API for `MNIST` and `FashionMNIST` looks like
```elixir
# Fetch images and labels together
{train_images, train_labels} = Axon.Data.MNIST.download()

# Or get them separately
train_images = Axon.Data.MNIST.download_images()
train_labels = Axon.Data.MNIST.download_labels()
```

Right now `Axon.Data.CIFAR` only supports `download/1` which returns the image/label tuple.

I'm not sure exactly where these modules should be located in the repo--I'd greatly appreciate feedback on that and any other suggestions!

### CODE REVIEW

**Comment by josevalim** [comment]
What if move this outside of Axon into a separate datasets library? 🤔 For example, I can see using datasets in dev/test but there is no need to have it in prod.

**Comment by seanmor5** [comment]
I agree with @josevalim I really like the idea of having this in a separate library. Something similar to Torchvision, Torchtext, etc. It looks like the framework is already mostly there as well for downloading the datasets.

**Comment by t-rutten** [comment]
A separate library makes sense. Should it be inside the Axon repo, comparable to e.g. `exla` inside the Nx repo but alongside the `nx` project, or totally separate?

**Comment by josevalim** [comment]
A totally separate project. :) we will also move EXLA and Torchx outside of Nx at some point once they become more stable.

btw, should we return binaries on download or should we return tensors? I guess binaries are fine and more general purpose?

**Comment by nyo16** [comment]
> A totally separate project. :) we will also move EXLA and Torchx outside of Nx at some point once they become more stable.
> 
> btw, should we return binaries on download or should we return tensors? I guess binaries are fine and more general purpose?
The only maybe reason to have it in binaries is if you want to pass the images to another lib for image processing (if needed).

**Comment by t-rutten** [comment]
Returning tensors would be nice for immediate use with Axon and Nx: the user wouldn't have to worry about the shape of the dataset to process the binaries.

Image processing with another library would certainly be a reason to keep them as binaries or in a different format. @nyo16 do you have any elixir libs in mind? [Torchvision.datasets](https://pytorch.org/vision/stable/datasets.html#mnist) returns [PIL](https://pillow.readthedocs.io/en/stable/) images and conversion to tensors happens with a transform function. 

We could do something similar here by returning a tensor--converted from binary and with a `transform/1` option applied to it. Changes would be necessary as progress is made on #25.

**Comment by josevalim** [comment]
Could we make it return `{binary, type}`? So we just need to unpack it and call `Nx.from_binary`?

**Comment by t-rutten** [comment]
Maybe `{binary, type, shape}`?

**Comment by josevalim** [comment]
Sounds good to me!

**Comment by nyo16** [comment]
> Returning tensors would be nice for immediate use with Axon and Nx: the user wouldn't have to worry about the shape of the dataset to process the binaries.
> 
> Image processing with another library would certainly be a reason to keep them as binaries or in a different format. @nyo16 do you have any elixir libs in mind? [Torchvision.datasets](https://pytorch.org/vision/stable/datasets.html#mnist) returns [PIL](https://pillow.readthedocs.io/en/stable/) images and conversion to tensors happens with a transform function.
> 
> We could do something similar here by returning a tensor--converted from binary and with a `transform/1` option applied to it. Changes would be necessary as progress is made on #25.

I think this would be great. My cases are around augmentation of the image(s). I don't have a specific lib in mind.
I like your idea to pass an optional transformation.

**Comment by seanmor5** [comment]
@nyo16 With respect to augmenting images, you might be interested in: https://github.com/4rtemi5/imax

It is a pure Jax implementation of image augmentations and transformations. Theoretically, a library like that could be written entirely in `Nx` defn and then executed with something like EXLA to achieve the same effect without having to shell out to PIL or another library. Although, I assume PIL and others probably have more efficient implementations.

**Comment by t-rutten** [comment]
I've moved the changes in this PR to a different repo: https://github.com/t-rutten/axon_datasets. 
`download/1` returns a tuple like `{binary_data, tensor_type, shape}` and accepts transformation options. Further suggestions are totally welcome.

Per #52, I'd be happy to port current examples to Live Markdown files that utilize AxonDatasets via `Mix.install/2` if that would be helpful.

**Comment by josevalim** [comment]
Thanks @t-rutten! @seanmor5, should we have them inside the elixir-nx organization? Are you ok with this too, @t-rutten? Also, I am thinking we don't need `Axon` in the name, as they should be general purpose?

**Comment by seanmor5** [comment]
@josevalim If it is okay with @t-rutten I think it makes sense to have them in the organization so it's more visible. I would also drop Axon from the name so they are more general purpose for other ML libraries

**Comment by josevalim** [comment]
Btw, the package name "datasets" is taken though, any suggestions?

**Comment by t-rutten** [comment]
Sure thing, let's move the repo to the organization.

NxDatasets? NxData? Nx is more general purpose than Axon...

**Comment by josevalim** [comment]
Yeah but this isn't Nx related either. :D Which kinda of datasets are we going to keep? Maybe we can use something like that for the name?

**Comment by batate** [comment]
ExDatasets?

Short, easy to type, shaped for Elixir consumption.

**Comment by batate** [comment]
Good for SEO: DataScienceSets?

Short and descriptive, but not overly descriptive: Corpus? ExCorpus?

-bt

**Comment by t-rutten** [comment]
We can start with computer vision related datasets and add text ones later (I do like ExCorpus @batate).

Maybe ExVision? VisionData? ImageData?

**Comment by batate** [comment]
ExCorpus.* seems pretty good to me. 

ExCorpus.Vision
ExCorpus.Stats
ExCorpus.xxx

seems like a good start.

**Comment by t-rutten** [comment]
I feel like "corpus" denotes language and text. @batate maybe your first suggestion, ExDatasets, is best: ExDatasets.Image, ExDatasets.Text, ExDatasets.Audio.

**Comment by josevalim** [comment]
Not a big fan of `Ex` prefixes... :D Based on your suggestions, I could think of: science_data / scidata / scisets / scidatasets / sci_datasets. I like scidata/Scidata.

**Comment by batate** [comment]
scidata is excellent.

**Comment by t-rutten** [comment]
I like scidata!

**Comment by josevalim** [comment]
Perfect! @t-rutten, I have created a repo in this organization, alongside a team, and gave you access: https://github.com/elixir-nx/scidata

Feel free to push or submit a PR to the scidata repo accordingly. :)

**Comment by t-rutten** [comment]
Great, thanks @josevalim!

**Comment by josevalim** [comment]
@t-rutten I pushed an initial commit with the LICENSE and made sure you have the proper write permissions. :)

**Pull request closed without merging**
